# NLP: Text Representation - Bag Of Words (BOW)

In [1]:
pip install pandas numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("spam.csv")
df.head()

cd                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.cd.value_counts()

cd
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['Category1'] = df['cd']
df.head()

cd                                            Message Category1
0   ham  Go until jurong point, crazy.. Available only ...       ham
1   ham                      Ok lar... Joking wif u oni...       ham
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...      spam
3   ham  U dun say so early hor... U c already then say...       ham
4   ham  Nah I don't think he goes to usf, he lives aro...       ham

In [6]:
df.rename(columns={'cd': 'Category'}, inplace=True)

In [7]:
df.head()

Category                                            Message Category1
0      ham  Go until jurong point, crazy.. Available only ...       ham
1      ham                      Ok lar... Joking wif u oni...       ham
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...      spam
3      ham  U dun say so early hor... U c already then say...       ham
4      ham  Nah I don't think he goes to usf, he lives aro...       ham

In [8]:
df.drop(df.columns[-1], axis=1, inplace=True)

In [9]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
df['Spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [11]:
df.shape

(5572, 3)

### Train Test Split

In [14]:
pip install scikit-learn

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------------------------- ------------ 41.0/60.8 kB 326.8 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 361.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
    --------------------------------------- 0.2/8.0 MB 4.0 MB/s eta 0:00:02
   - -------------------------------------- 0.4/8.0 MB 4.7 MB/s eta 0:00:02
   --- ------------------------------------ 0.6/8.0 MB 5.7 MB/s eta 0:00:02
   ---- ----------------------------------- 0.9/8.0 MB 5.3 MB/s eta 0:00:02
   ----- ---------------------------------- 1.2/8.0 MB 5.7 MB/s eta 0:00:02
   ------- -------------------------------- 1.5/8.0 MB 5.5 MB/s eta 0:00:02
   -------- ------------------------------- 1.7/8.0 MB 5.7 MB/s eta 0:00:02
   --------- ---------


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Spam, test_size=0.2)

In [17]:
X_train.shape

(4457,)

In [18]:
X_test.shape

(1115,)

In [19]:
y_train.shape

(4457,)

In [20]:
y_test.shape

(1115,)

In [21]:
X_train[:4]

5273           Its too late:)but its k.wish you the same.
4923    Hi Dear Call me its urgnt. I don't know whats ...
126                                  Good stuff, will do.
3738    Plz note: if anyone calling from a mobile Co. ...
Name: Message, dtype: object

In [22]:
X_test[:4]

361                Ha ha cool cool chikku chikku:-):-DB-)
654                            Fine i miss you very much.
3309    But i'm surprised she still can guess right lo...
26                         Lol your always so convincing.
Name: Message, dtype: object

In [23]:
y_train[:4]

5273    0
4923    0
126     0
3738    0
Name: Spam, dtype: int64

In [24]:
y_test[:4]

361     0
654     0
3309    0
26      0
Name: Spam, dtype: int64

#### Create bag of words representation using CountVectorizer

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59601 stored elements and shape (4457, 7743)>

In [29]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7743))

In [30]:
X_train_cv.shape

(4457, 7743)

In [34]:
v.get_feature_names_out()[3757]

'its'

In [35]:
v.vocabulary_

{'its': 3757,
 'too': 6974,
 'late': 4021,
 'but': 1571,
 'wish': 7545,
 'you': 7705,
 'the': 6816,
 'same': 5889,
 'hi': 3418,
 'dear': 2188,
 'call': 1603,
 'me': 4397,
 'urgnt': 7218,
 'don': 2405,
 'know': 3952,
 'whats': 7481,
 'your': 7710,
 'problem': 5428,
 'want': 7384,
 'to': 6934,
 'work': 7597,
 'or': 4975,
 'if': 3592,
 'have': 3351,
 'any': 990,
 'other': 5000,
 'at': 1117,
 'least': 4055,
 'tell': 6753,
 'wating': 7411,
 'for': 2932,
 'reply': 5714,
 'good': 3178,
 'stuff': 6545,
 'will': 7524,
 'do': 2370,
 'plz': 5264,
 'note': 4824,
 'anyone': 994,
 'calling': 1616,
 'from': 3015,
 'mobile': 4544,
 'co': 1864,
 'amp': 947,
 'asks': 1098,
 'type': 7115,
 'lt': 4240,
 'gt': 3252,
 'not': 4823,
 'so': 6279,
 'disconnect': 2342,
 'coz': 2047,
 'it': 3750,
 'iz': 3767,
 'an': 955,
 'attempt': 1128,
 'of': 4887,
 'terrorist': 6778,
 'make': 4312,
 'use': 7230,
 'sim': 6168,
 'card': 1647,
 'no': 4790,
 'itz': 3761,
 'confirmd': 1959,
 'by': 1586,
 'nokia': 4799,
 'motorola'

In [36]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7743,))

In [37]:
np.where(X_train_np[0] != 0)

(array([1571, 3757, 4021, 5889, 6816, 6974, 7545, 7705]),)

### Train the naive bayes model

In [38]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [39]:
X_test_cv = v.transform(X_test)

In [40]:
X_test_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13464 stored elements and shape (1115, 7743)>

#### Evaluate Performance

In [42]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       966
           1       0.98      0.91      0.94       149

    accuracy                           0.99      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [43]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

email_counts = v.transform(emails)
model.predict(email_counts)

array([0, 1])

#### Train the model using sklearn pipeline and reduce number of lines of code

In [44]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [45]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [46]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       966
           1       0.98      0.91      0.94       149

    accuracy                           0.99      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115

